from banksia import Metadata

__all__ = ["METADATA"]

METADATA: list[Metadata] = [
    Metadata(
        "DM1",
        "Dysmorphology - eyes",
        var_type="nominal",
        field_values={
            1: "Convergent strabismus - manifest",
            2: "Convergent strabismus - latent",
            3: "Divergent strabismus - manifest",
            4: "Divergent strabismus - latent",
            5: "Unequal pupils",
            6: "Non-reactive pupils",
            7: "Other pupillary abnormalities",
            8: "Corneal opacity",
            9: "Cataract(s) or other lens opacity",
            10: "Lens dislocation",
            11: "Retinal pigmentation",
            12: "Abnormal irides",
            13: "Other coloboma",
            14: "Microphthalmos",
            15: "Short palpebral fissures",
            16: "Upslanting palpebral fissures (mongoloid slant)",
            17: "Downslanting palpebral fissures (anti-mongoloid slant)",
            18: "Hypertelorism",
            19: "Hypotelorism",
            20: "Epicanthic folds",
            21: "Ptosis",
            22: "Abnormal eyebrows",
            23: "Conjunctivitis",
            24: "Tearing",
            25: "Subconjunctival hemorrhage",
            26: "Other",
            -99: "Missing",
            -88: "N/A",
        },
    ),
    Metadata(
        "DM2",
        "Dysmorphology - ears",
        var_type="nominal",
        field_values={
            "1": "Low-set ears",
            "2": "Rotated ears",
            "3": "Pre-auricular tags/pits",
            "4": "Malformed auricles",
            "5": "Small ears",
            "6": "Upward take-off of lobe",
            "7": "Retraction of tympanic membrane(s)",
            "8": "Middle ear effusion",
            "9": "Inflammation of tympanic membrane(s)",
            "10": "Scarring of tympanic membrane(s)",
            "11": "Prominent/bat ears",
            "12": "Grommets (tympanostomy tubes) in situ",
            "13": "Creased lobes",
            "14": "Abnormal helix",
            "15": "Tympanosclerosis",
            "16": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM3",
        "Dysmorphology - skull",
        var_type="nominal",
        field_values={
            "1": "Abnormal shape- scaphocephaly",
            "2": "Brachycephaly/flat occiput",
            "3": "Prominent occiput",
            "4": "Plagiocephaly",
            "5": "Wide sutures",
            "6": "Raised sutures",
            "7": "Frontal bossing",
            "8": "Wide fontanelle",
            "10": "Cranial bruit",
            "11": "Macrocephaly (> 98th percentile)",
            "12": "Microcephaly (< 2nd percentile)",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM4",
        "Dysmorphology - skin",
        var_type="nominal",
        field_values={
            "1": "Pallor",
            "2": "Plethora",
            "3": "Cyanosis(central)",
            "4": "Cyanosis(peripheral)",
            "5": "Jaundice",
            "6": "Thickened skin/ichthyosis/keratosis pilaris",
            "7": "Hyperpigmentation (generalised)",
            "8": "Cafe au lait spots",
            "9": "Naevi",
            "10": "Albinism",
            "11": "Depigmented patches",
            "12": "Pityriasis versicolor",
            "13": "Haemangiomata",
            "14": "Telangiectases",
            "15": "Other cysts/tumours/hamartomata",
            "16": "Bruising/petechiae",
            "17": "Hypohidrosis",
            "18": "Eczema (atopic dermatitis)",
            "19": "Saborrhoeic dermatitis (incl. cradle cap)",
            "20": "Miliaria",
            "21": "Psoriasis",
            "22": "Napkin dermatitis",
            "23": "Other erythematous rash",
            "24": "Acne/pustules/contagious infection",
            "25": "Hirsutism",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM5",
        "Dysmorphology - spine",
        var_type="nominal",
        field_values={
            "1": "Scoliosis",
            "2": "Kyphosis",
            "3": "Lordosis",
            "4": "Abnormal swelling",
            "5": "Spina bifida",
            "6": "Sacral dimple/naevus/haemangioma/hairy tuft",
            "7": "Pilonidal sinus",
            "8": "Mongolian spot",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM6",
        "Dysmorphology - heart",
        var_type="nominal",
        field_values={
            "1": "Hyperdynamic pulses",
            "2": "Absent brachial pulse(s)",
            "3": "Weak/absent femoral pulse(s)",
            "4": "Cardiomegaly/displaced apex",
            "5": "Abnormal heart sounds",
            "6": "Thrill",
            "7": "Murmur - innocent",
            "8": "Murmur - other",
            "26": "Irregular rhythm",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM7",
        "Dysmorphology - female genitals",
        var_type="nominal",
        field_values={
            "1": "Hypoplastic labia majora",
            "2": "Clitoral hypertrophy",
            "3": "Short recto-vaginal distance",
            "4": "Labial adhesions",
            "5": "Abnormal hymen",
            "6": "Labial/pubic hair",
            "7": "Vaginal tags",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM8",
        "Dysmorphology - nose",
        var_type="nominal",
        field_values={
            "1": "Rhinorrhoea (not crying)",
            "2": "Nasal obstruction/mouth breathing",
            "3": "Low nasal bridge",
            "4": "Broad nasal bridge",
            "5": "Small or short nose",
            "6": "Bulbous, large or prominent nose",
            "7": "Anteverted nares",
            "8": "Hypoplastic nares",
            "9": "Scarred nares",
            "10": "Long philtrum",
            "11": "Short philtrum",
            "12": "Prominent/deep philtrum",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM9",
        "Dysmorphology - jaw",
        var_type="nominal",
        field_values={
            "1": "Micrognathia",
            "2": "Prognathism",
            "3": "Fine/pointed jaw",
            "26": "Asymmetry",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM10",
        "Dysmorphology - hair",
        var_type="nominal",
        field_values={
            "1": "Sparse hair",
            "2": "Alopecia",
            "3": "Coarse/wiry hair",
            "4": "Low posterior hair line",
            "5": "Widow's peak",
            "6": "Double crown",
            "7": "Hypopigmented albinism",
            "8": "Hirsute facies",
            "12": "Infestation or infection",
            "13": "White forelock",
            "14": "Electric hair",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM11",
        "Dysmorphology - hands",
        var_type="nominal",
        field_values={
            "1": "Small hands",
            "2": "Brachydactyly (short fingers)",
            "3": "Arachnodactyly (long fingers)",
            "4": "Broad fingers",
            "5": "Clinodactyly",
            "6": "Other finger anomalies",
            "7": "Broad thumbs",
            "8": "Digitalised thumbs",
            "9": "Hypoplastic thumb(s)",
            "10": "Other thumb anomalies",
            "11": "Syndactyly",
            "12": "Polydactyly",
            "13": "Hypoplastic/dysplastic nails",
            "14": "Single crease 5th (little) finger",
            "15": "Single palmar (simian) crease",
            "16": "Short metacarpals",
            "17": "Clubbing",
            "18": "Leukonychia",
            "19": "Paronychia",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM12",
        "Dysmorphology - joints",
        var_type="nominal",
        field_values={
            "1": "Hypermobility",
            "2": "Restricted movements/contractures - small joints of hand",
            "3": "Restricted movements/contractures - wrists",
            "4": "Restricted movements/contractures - elbows",
            "5": "Restricted movements/contractures - shoulders",
            "6": "Restricted movements/contractures - hips",
            "7": "Restricted movements/contractures - knees",
            "8": "Restricted movements/contractures - ankles",
            "9": "Restricted movements/contractures - neck/spine",
            "10": "Swelling/inflammation - interphalangeal",
            "11": "Swelling/inflammation - metacarpophalangeal",
            "12": "Swelling/inflammation - wrists",
            "13": "Swelling/inflammation - elbows",
            "14": "Swelling/inflammation - shoulders",
            "15": "Swelling/inflammation - hips",
            "16": "Swelling/inflammation - knees",
            "17": "Swelling/inflammation - ankles",
            "18": "Swelling/inflammation - neck/spine",
            "19": "Absent patellae",
            "20": "Dislocated hips",
            "21": "Other joint dislocations",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM13",
        "Dysmorphology - abdomen",
        var_type="nominal",
        field_values={
            "1": "Enlarged/distended",
            "2": "Ascites",
            "3": "Hepatomegaly",
            "4": "Splenomegaly",
            "5": "Enlarged left kidney",
            "6": "Enlarged right kidney",
            "7": "Enlarged bladder",
            "8": "Faecal masses",
            "9": "Other masses",
            "10": "Umbilical hernia",
            "11": "Inguinal hernia",
            "12": "Abnormal anus",
            "13": "Abnormal bruit",
            "14": "Diastasis recti",
            "15": "Enlarged lymph nodes",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM14",
        "Dysmorphology - mouth",
        var_type="nominal",
        field_values={
            "1": "Microstomia",
            "2": "Macrostomia",
            "3": "Prominent lips",
            "4": "Downturning corners of mouth",
            "5": "Lip pits",
            "6": "Cleft lip",
            "7": "Cleft lip and palate",
            "8": "Cleft palate without cleft lip",
            "9": "Submucous cleft",
            "10": "Bifid uvula",
            "11": "High-arched palate",
            "12": "Ridged palate",
            "13": "Macroglossia",
            "14": "Irregular or amputated tongue",
            "15": "Tongue-tie",
            "16": "Hypodontia",
            "17": "Enamel hypoplasia",
            "18": "Dental caries",
            "19": "Mesiodens",
            "20": "Other anomalies of teeth",
            "21": "Hypertrophied alveolar margin",
            "22": "Epulis or dental cysts",
            "23": "Mouth ulcers/stomatitis",
            "24": "Pharyngitis/tonsillitis",
            "25": "Crowding of posterior oropharynx/tonsillar hypertrophy",
            "26": "Chipped stained or wide gaps in teeth",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM15",
        "Dysmorphology - face",
        var_type="nominal",
        field_values={
            "1": "Fat, puffy midface",
            "2": "Flat midface",
            "3": "Malar hypoplasia",
            "4": "Maxillary hypoplasia",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM16",
        "Dysmorphology - neck",
        var_type="nominal",
        field_values={
            "1": "Short neck",
            "2": "Webbed neck/redundant skin",
            "3": "Sternomastoid tumour",
            "4": "Cysts",
            "5": "Sinuses",
            "6": "Lymphadenopathy",
            "7": "Goitre",
            "8": "Tracheostomy",
            "16": "Enlarged lymphnodes",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM17",
        "Dysmorphology - chest",
        var_type="nominal",
        field_values={
            "1": "Small chest",
            "2": "Hyperexpanded (barrel) chest",
            "3": "Pectus excavatum (sunken chest)",
            "4": "Pectus carinatum (pigeon chest)",
            "5": "Harrison's sulcus",
            "6": "Intercostal/suprasternal recession",
            "7": "Tachypnoea at rest",
            "8": "Deviated trachea",
            "9": "Unequal air entry",
            "10": "Wheezing (rhonchi, rales)",
            "11": "Crackles (crepitations)",
            "12": "Other adventitia",
            "13": "Widely spaced nipples",
            "14": "Other nipple anomalies",
            "15": "Abnormal clavicles",
            "16": "Stridor/croup",
            "17": "Gynaecomastia/breast enlargement",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM18",
        "Dysmorphology - male genitals",
        var_type="nominal",
        field_values={
            "1": "Undescended left testis",
            "2": "Undescended right testis",
            "3": "Testicular hypoplasia/atrophy",
            "4": "Hydrocoele",
            "5": "Short/small penis",
            "6": "Hypospadias",
            "7": "Chordee",
            "8": "Abnormal foreskin",
            "9": "Shawl scrotum",
            "10": "Bifid scrotum",
            "11": "Ambiguous genitalia",
            "12": "Circumcised",
            "13": "Pubic hair",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM19",
        "Dysmorphology - neurological features",
        var_type="nominal",
        field_values={
            "1": "Spasticity - quadriplegia",
            "2": "Spasticity - diplegia",
            "3": "Spasticity - hemiplegia",
            "4": "Hypotonia",
            "5": "Weakness - generalised",
            "6": "Weakness - localised",
            "7": "Muscle wasting - generalised",
            "8": "Muscle wasting - localised",
            "9": "Muscle hypertrophy",
            "10": "Abnormal sensation",
            "11": "Segmental denervation - arms",
            "12": "Segmental denervation - legs",
            "13": "Spinal cord lesion",
            "14": "Involuntary movements (chorea, athetosis)",
            "15": "Dystonia",
            "16": "Muscle fasciculation (incl. tongue)",
            "17": "Ataxia - truncal",
            "18": "Ataxia - appendicular (incl. dysdiadochokinesis, past-pointing)",
            "19": "Facial nerve palsy",
            "20": "Bulbar/pseudobulbar palsy",
            "21": "Extraocular nerve palsy",
            "22": "Unclear speech (incl. dysarthria, oral dyspraxia)",
            "23": "Clumsy (incl. motor dyspraxia)",
            "24": "Seizures (observed)",
            "25": "Tremor",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM20",
        "Dysmorphology - feet",
        var_type="nominal",
        field_values={
            "1": "Small feet",
            "2": "Short hallux",
            "3": "Broad hallux",
            "4": "Hammer/claw toe deformity",
            "5": "Syndactyly",
            "6": "Polydactyly",
            "7": "Other toe anomalies",
            "8": "Pes cavus",
            "9": "Pes planus",
            "10": "Short metatarsals",
            "11": "Prominent heels",
            "12": "Talipes equinovarus",
            "13": "Talipes (other)",
            "14": "Metatarsus varus (adductus)",
            "15": "Pigeon toed walk",
            "26": "Positional talipes",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
    Metadata(
        "DM21",
        "Dysmorphology - limbs",
        var_type="nominal",
        field_values={
            "1": "Short limbs",
            "2": "Limb deformity",
            "3": "Hemihypertrophy or hemiatrophy",
            "4": "Radial hypoplasia",
            "5": "Bow legs",
            "6": "Internal tibial torsion",
            "26": "Other",
            "-99": "Missing",
            "-88": "N/A",
        },
    ),
]

# (
#     Metadata(
#         "DM",
#         "Dysmorphology - ",
#         var_type="nominal",
#         field_values={},
#     ),
# )
